_target_: model.example_model.lightning_module.ExampleLightningModel
num_classes: 10
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
loss_fn:
  _target_: monai.losses.ContrastiveLoss
  temperature: 0.1 
  batch_size: -1
  _partial_: true
scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 5
  gamma: 0.1
  _partial_: true
